# Website settings
baseurl: "/"
url: "http://saptak.in"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Saptak Sen"
slogan: "Programmer, entrepreneur, writer, speaker, traveler"
description: "The home page of Yevgeniy (Jim) Brikman, founder of Atomic Squirrel, author of Hello, Startup, and software engineer at LinkedIn, TripAdvisor, Cisco Systems, and Thomson Financial."
thumbnail_path: "yevgeniy-brikman-medium.jpg"
bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
spark_book_url: "http://saptak.in/spark"
website_repo_url: "https://github.com/saptak/saptak.github.io"
hortonworks_url: "http://saptak.in/"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/saptak"
    label: "Twitter"
    icon: "twitter-square"
    username: "@saptak"
  linkedin:
    url: "https://www.linkedin.com/in/saptak"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/saptak"
    label: "Facebook"
    icon: "facebook-square"
  google:
    url: "https://plus.google.com/saptak/"
    label: "Google+"
    icon: "google-plus-square"
  slideshare:
    url: "https://www.slideshare.net/saptak"
    label: "SlideShare"
    icon: "slideshare"
  github:
    url: "https://github.com/saptak"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:sen@ysaptak.in"
    label: "Email"
    value: "sen@saptak.in"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: pygments
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
