excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://saptak.in
title: saptak.in
tagline: The filtered bits I am interested in.
description: The opinion I express on this site are mine and not of my employer
paginate: 1
